# Generated by Django 3.2 on 2021-05-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='phases_number',
            field=models.CharField(choices=[('1', 'Single Phase'), ('3', 'Three Phase')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='power',
            field=models.CharField(choices=[('1.0', '1.0'), ('2.0', '2.0'), ('3.0', '3.0'), ('5.0', '5.0'), ('10.0', '10.0')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='purpose',
            field=models.CharField(choices=[('General', 'General Purpose'), ('Pump', 'Pump')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='speed',
            field=models.CharField(choices=[('1200', '1200'), ('1800', '1800'), ('3600', '3600')], max_length=10, null=True),
        ),
    ]
