# Generated by Django 3.2 on 2021-05-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210505_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purpose',
            field=models.CharField(choices=[('General Purpose', 'General Purpose'), ('Pump', 'Pump'), ('Fan', 'Fan')], max_length=15, null=True),
        ),
    ]
