# Generated by Django 3.2 on 2021-05-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='power',
            field=models.CharField(blank=True, choices=[('1.0', '1.0'), ('2.0', '2.0'), ('3.0', '3.0'), ('5.0', '5.0'), ('10.0', '10.0')], max_length=10, null=True),
        ),
    ]
